### ISSUE TITLE
can't run the image

### ISSUE THREAD

**Issue by ozbillwang** [tonybaloney/mocker#2]
mocker.py with **pull** and **images** are fine. But when try to run **nginx** or **hello-world**, got same error: 

```
$ ./mocker.py run library/nginx
Traceback (most recent call last):
  File "./mocker.py", line 22, in <module>
    cls.run(**arguments)
  File "github/tonybaloney/mocker/mocker/run.py", line 53, in run
    with IPDB() as ipdb:
  File "/usr/local/lib/python2.7/site-packages/pyroute2/__init__.py", line 125, in __new__
    cls.register(cls.registry['class'])
  File "/usr/local/lib/python2.7/site-packages/pyroute2/__init__.py", line 105, in __getitem__
    [name], 0)
  File "/usr/local/lib/python2.7/site-packages/pyroute2/ipdb/main.py", line 533, in <module>
    from pyroute2.iproute import IPRoute
  File "/usr/local/lib/python2.7/site-packages/pyroute2/iproute.py", line 175, in <module>
    from socket import AF_BRIDGE
ImportError: cannot import name AF_BRIDGE
```

**Comment by ozbillwang** [comment]
@tonybaloney 

Is it because I run it directly on mac?  Does it only work on linux?

**Comment by tonybaloney** [comment]
Absolutely this will only work on Linux. In fact I'm surprised the packages even install on mac

**Comment by ozbillwang** [comment]
run without problem in centos 7. 

👍
